### ISSUE TITLE
Change name of `map` function

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/strikt#103]
In order to accommodate having a `map` function that is ```Assertion.Builder<Iterable<T>>((Iterable<T>) -> Iterable<R>) -> Assertion.Builder<Iterable<R>>``` it's necessary to change the name of the existing `map` function.

**Comment by robfletcher** [comment]
I propose changing the existing `map` to `mapTo` then adding a new `map` that operates on `Assertion.Builder<Iterable<E>>`.

**Comment by robfletcher** [comment]
Possible names:

- `chain`
- `mapTo` (conflicts with stdlib method on `Iterable`)
- `traverse`

**Comment by christophsturm** [comment]
Why not keep the old map as map and use  map { it.map { ... } } if you want to map something?

**Comment by robfletcher** [comment]
I just think that looks awful (I found myself doing it a couple of times at work). Doing this kind of map on an iterable is pretty common.
