### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by nbransby** [robfletcher/strikt#113]
Does this library only work on the jvm or is it implemented in pure Kotlin?

**Comment by robfletcher** [comment]
It's implemented in pure Kotlin. However I'm not sure what would be needed in order for it to work with JS / Native. 

There's an open issue #100 for JS support. It's not a super-high priority for me personally as I'm using Strikt purely for JVM work and have never done anything with Kotlin JS or Native. I'm very open to any discussion on Slack / here or pull requests.

**Comment by nbransby** [comment]
Just had a quick flick through the code and can see lots of `import java....` statements so it would not be  straightforward to turn this into multiplatform project

**Comment by robfletcher** [comment]
There are 4 files that import from something other than `kotlin.*` or other parts of Strikt:

 * `Any.kt` uses `java.beans.Introspector` to implement `propertiesAreEqualTo`.
 * `FilePeek.kt` uses `java.io.File` to read source code files.
 * `ResultWriter.kt` uses `java.io.StringWriter` to append error messages to a string.
 * `TemporalAccessor.kt` imports a bunch of classes from `java.time` and provides extension functions for assertions on them.

The first and second are optional, non-core behavior. The third could be implemented differently. The last could be moved out of core to a `strikt-jvm` module.

That's only counting production files, not tests.

**Comment by robfletcher** [comment]
Closing as sub-task of #100
