### ISSUE TITLE
Generate changelogs for each release

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/strikt#116]

**Comment by cjbrooks12** [comment]
Are you wanting them to be generated based on git, or managed manually? Orchid has a [Changelog plugin](https://orchid.netlify.com/plugins/OrchidChangelog) we could get set up with. Right now it just manages versions based on markdown files, but I could look into pulling changelogs from git tags or something like that.

**Comment by robfletcher** [comment]
Whatever works, honestly.

**Comment by robfletcher** [comment]
Fixed by migration to Orchid
