### ISSUE TITLE
Collection assertions for sorted status

### ISSUE THREAD

**Issue by sandjelkovic** [robfletcher/strikt#124]
Currently there is no way to assert if a collection is sorted or not and it would be great if we could have something that we could use out of the box and not write Custom Assertions for it every time.

Similar as [AssertJ isSortedAccordingTo](http://javadox.com/org.assertj/assertj-core/3.1.0/org/assertj/core/api/AbstractListAssert.html#isSortedAccordingTo-java.util.Comparator-)

Example for one of possible assertions:
```
fun <T : Collection<E>, E : Any> Assertion.Builder<T>.isSorted(comparator: Comparator<E>) =
    assert("is sorted") { actual ->
        for (index in 0 until (actual.size - 1)) {
            if (comparator.compare(actual.elementAt(index), actual.elementAt(index + 1)) > 0)
                fail(
                    actual,
                    "${actual.elementAt(index)} is greater than ${actual.elementAt(index + 1)}"
                )
        }
        pass()
    }
```

**Comment by robfletcher** [comment]
Definitely a good idea.
