### ISSUE TITLE
Catching lambda doesn't output the excpetion's message

### ISSUE THREAD

**Issue by dave08** [robfletcher/strikt#131]
If I assert `expectThat(catching { ... }).isNull()`, and it throws, it doesn't print the exception's message... 

In my case: 
```
▼ Expect that com.squareup.moshi.JsonDataException:
  ✗ is null
```
which doesn't help too much to identify the source of the problem.

As a plus, it would be nice to have `expectDoesNotThrow { }`, that would allow to add more checks on a valid result.

**Comment by mkobit** [comment]
Any thoughts around the best UX for this?

[AssertJ's](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractThrowableAssert.html#doesNotThrowAnyException--) pattern for this looks like:

```java
assertThatCode(() -> foo.bar()).doesNotThrowAnyException();
```

Which I have found myself using a decent amount.

**Comment by robfletcher** [comment]
Something like that would be much better than the current implementation. Maybe `expectRunning` or `expectExecuting`?

**Comment by mkobit** [comment]
I don't think I have a strong preference for which variant to include. I would like to have the one-function style compared to the current `expectThat(catching { }).isNull()` and the AssertJ example above.

JUnit 5 `Asserions` also has [`assertDoesNotThrow`](https://github.com/junit-team/junit5/blob/dea4bb831c6cd3facf88770d2da8bc2cfe0d9ef5/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java#L3004-L3006). The Kotlin variants that are going to be introduced in `5.5` returns the value of the supplied execution, too.

```kotlin
val result = assertDoesNotThrow {
  5
}
// assert on result
```

I guess it just a matter of somebody picking a name /shrug

* `expectDoesNotThrow {}.chainedAssertion()`
* `expectRunning {}.chainedAssertion()`
* `expectExecuting {}.chainedAssertion()`
* `expectRunning {}.chainedAssertion()`


I think `.chainedAssertion()` makes sense here, as the result of `expectXXXXX {}` would return an `Assertion.Builder` to allow users to assert on the possible returned result.

Any thoughts or executive decision?

**Comment by robfletcher** [comment]
I'm working on something at the moment that does away with `catching` altogether. Kotlin already has the `runCatching` method. Instead of dealing with an exception or `null` we can use `runCatching` to produce a `Result<T>` that is either the value (as returned by the lambda) or the exception it threw. I think this makes much more sense for asserting against.

**Comment by robfletcher** [comment]
Fixed with new `expectCatching` … `failed` construct (or existing `expectThrows`).
