### ISSUE TITLE
Type safety in containsExactly

### ISSUE THREAD

**Issue by f4lco** [robfletcher/strikt#137]
As per https://strikt.io/wiki/flow-typing/, I did not expect the following example to compile:

```kotlin
import org.junit.jupiter.api.Test
import strikt.api.expectThat
import strikt.assertions.containsExactly
import strikt.assertions.map

class StriktTest {

    data class Person(val name: String)

    @Test
    fun `why does this compile?`() {
        val subject: List<Person> = listOf(Person("foo"), Person("bar"))

        expectThat(subject).containsExactly("foo", "bar")
    }
}
```

Which gives us the (correct) result:

> org.opentest4j.AssertionFailedError: ▼ Expect that [Person(name=foo), Person(name=bar)]:
  ✗ contains exactly the elements ["foo", "bar"]
    ✗ contains "foo"
    ✗ contains "bar"
    ✗ contains no further elements : found [Person(name=foo), Person(name=bar)]

Is this the expected behavior? Is there any wrongdoing from my side, except for the typing error? Since I'm not that into Kotlin (yet), I would like to learn about if this is the best type safety Kotlin / the current design can offer, about potential fixes, and if there are similar situations for other assertion methods.

Kotlin 1.3.20 / Strikt 0.17.2

**Comment by robfletcher** [comment]
I confess that is not what I expected. It appears like the type is getting widened to `List<Any>` because of the arguments getting passed. If I specify the generic type of the method call itself the compilation fails: ```
expectThat(subject).containsExactly<List<Person>, Person>("foo", "bar")
```

**Comment by robfletcher** [comment]
Confirming that it's to do with variance, I tried a similar construction using a `Map` subject (where the key does _not_ have `out` variance). Indeed this does not compile:
```
expectThat(mapOf("foo" to "bar")).containsKey(1)
```

**Comment by f4lco** [comment]
Based on your comments I conducted further research and have come to the following conclusions. There are two cases:

1. Above behaviour is legit / expected, because `contains` is expressed in terms of `equals`, and nobody 'fixed' its signature: [`equals(other: Any?): Boolean`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/equals.html). Therefore it has to be possible to pass unrelated types to `containsExactly`, because objects can be equal to each other regardless of their types.
2. The assertion method should work similar to `List.contains` from the Kotlin collections library: [`contains(element: E): Boolean`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list/contains.html) ('fixed' / type safe alternative to [`java.util.List.contains(Object)`](https://docs.oracle.com/javase/7/docs/api/java/util/List.html#contains(java.lang.Object))). 

Regarding option (2), I learned that the Kotlin standard library suppresses widening the type by using a special assertion: `@OnlyInputTypes`. For instance, the full signature for contains on Iterables:

    public operator fun <@kotlin.internal.OnlyInputTypes T> Iterable<T>.contains(element: T): Boolean

Based on: https://discuss.kotlinlang.org/t/restrict-type-by-receiver/5492
If we consider restricting input types using the annotation, we will have to wait for it to become public API of Kotlin: https://youtrack.jetbrains.com/issue/KT-13198
If this indeed covers the use case we are discussing, I deem it a worthy change to strikt.

**Comment by robfletcher** [comment]
Yeah, that would 100% make sense. I'll keep an eye on that issue.

**Comment by tamj0rd2** [comment]
Maybe there could be a warning about this added to the documentation of `containsExactly`? It took me a while to find this issue.
