### ISSUE TITLE
Support quantitative assertions

### ISSUE THREAD

**Issue by mkobit** [robfletcher/strikt#140]
AssertJ has several assertions variants like the following [`ObjectEnumerableAssert`](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/ObjectEnumerableAssert.html):

* `areAtLeast(int n, Condition<? super ELEMENT> condition)`
* `areAtMost(int n, Condition<? super ELEMENT> condition)`
* `areExactly(int n, Condition<? super ELEMENT> condition)`
* `areNot(Condition<? super ELEMENT> condition)`
* `are(Condition<? super ELEMENT> condition)`

It would be useful to be able to do a similar thing in `strikt`.

**Comment by robfletcher** [comment]
Sure. We have `all`, `any`, and `none` but these would also make sense.
