### ISSUE TITLE
Consider adding a `strikt-gradle` module

### ISSUE THREAD

**Issue by mkobit** [robfletcher/strikt#150]
For use with https://docs.gradle.org/current/userguide/test_kit.html and possibly other components of the Gradle API.

I would definitely be willing to contribute all the things we currently use (which is all just testkit stuff), just wondering if you think this project is a suitable home for it.

**Comment by robfletcher** [comment]
Seems reasonable, yeah.

**Comment by mkobit** [comment]
Thanks for merging and releasing https://github.com/robfletcher/strikt/pull/155 so quickly - I think maybe a Bintray switch somewhere might need to be flipped unless I screwed up the publishing bits.

**Comment by robfletcher** [comment]
I have to request each new sub-module be included on JCenter. Turnaround is normally a couple of hours. In the mean time it should be available from `https://dl.bintray.com/robfletcher/maven`.

**Comment by robfletcher** [comment]
Implemented in #155
