### ISSUE TITLE
Add assertions for sequence/subsequence of values being present in a List

### ISSUE THREAD

**Issue by mkobit** [robfletcher/strikt#156]
In AssertJ there are a few assertions for asserting that the provided sequence of values exists in a  `List` (possibly other types as well) in a contiguous manner (or non-contiguous),

From AssertJ

* [`containsSequence(ELEMENT... sequence)`](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/ListAssert.html#containsSequence-ELEMENT...-)

    > Verifies that the actual group contains the given sequence in the correct order and without extra values between the sequence values.

* [`containsSubsequence(ELEMENT... sequence)`](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/ListAssert.html#containsSubsequence-ELEMENT...-)

    > Verifies that the actual group contains the given subsequence in the correct order (possibly with other values between them).

I suggest to add similar assertions to `strikt` 

```kotlin
expectThat(listOf(1,2,3,4)) {
    containsSequence(2, 3)
    containsSubsequence(1,4)
    not { containsSequence(2, 4) }
    not { containsSubsequence(4, 2) }
}
```

**Comment by robfletcher** [comment]
Fixed by #184
