### ISSUE TITLE
Consider making Iterable.contains behavior for empty collections behave similar to stdlib

### ISSUE THREAD

**Issue by mkobit** [robfletcher/strikt#160]
I believe that the `contains` for both empty subjects and empty elements should be different than the current behavior.

The current behavior for `expectThat(emptyList).contains(emptyList())` and `expectThat(listOf(1)).contains(emptyList())` both fail when, what I consider to be the `stdlib` equivalents of `containsAll` both succeed.

```kotlin
internal class Mk {
  @TestFactory
  internal fun contains() = testFactory<List<Int>> {
    context("empty list") {
      fixture { emptyList() }

      context("contains empty") {
        test("strikt behavior") {
          expectThat(fixture).contains(emptyList())
        }
        test("stdlib behavior") {
          expectThat(fixture.containsAll(emptyList())).isTrue()
        }
      }
    }
    context("list with element") {
      fixture { listOf(1) }
      context("contains empty") {
        test("strikt behavior") {
          expectThat(fixture).contains(emptyList())
        }
        test("stdlib behavior") {
          expectThat(fixture.containsAll(emptyList())).isTrue()
        }
      }
    }
  }
}
```

Both `stdlib` tests above pass but both `strikt` fail with

```
java.lang.IllegalArgumentException: You must supply some expected elements.
```

**Comment by robfletcher** [comment]
Yeah, consistency would make sense.

**Comment by robfletcher** [comment]
I'm somewhat torn about this. On the one hand consistency with the standard library makes sense, but at the same time using `contains(emptyList())` seems nonsensical (I guess in certain generative testing scenarios it might end up getting called but aside from that). _Any_ collection always contains the empty list.
