### ISSUE TITLE
Add method like 'isEqualToIgnoringGivenFields'

### ISSUE THREAD

**Issue by levelast** [robfletcher/strikt#167]
Hey!

May you add method like 'isEqualToIgnoringGivenFields' from AssertJ or assertk? It'll be very useful in many cases. I know strikt has method 'propertiesAreEqualTo', but it hasn't ignored fields in signature.

Task about adding this functionality to assertk: https://github.com/willowtreeapps/assertk/issues/194

Thank you for this cool library and sorry for my English =)

**Comment by efenderbosch** [comment]
Another option for syntax is something like `ignoring(MyEntity::updatedAt, MyEntity::updatedBy).isEqualTo(expected)`

I made a custom matcher for hamkrest like this and found the syntax to be very readable.
