### ISSUE TITLE
improve `strikt.api.Assertion.Builder.get(...)`

### ISSUE THREAD

**Issue by tmohme-hypoport** [robfletcher/strikt#179]
While the functionality is quite convenient, using the `get` function with a lambda comes with a comparatively heavy performance penalty.

We were hit by this because of a unfortunate combination of two things:
- We heavily use property-based testing, hence our tests will get executed hundreds of times
- "Using get with Lambdas" is the first paragraph in the user guide and lambdas are the most concise form so we used it even if we could as well have used the property form. We overlooked the note "Strikt will read the test source to find out the name of the variables".

The easiest way to warn others about this pitfall would be to make the already existing warning more prominent.
A (from user perspective) more robust solution would be, to determine the fieldname lazy, only when needed (i.e. the test failed and some output will actually produced). 

We are using the current version 0.21.1

**Comment by robfletcher** [comment]
Sounds like we should implement lazy resolution at the very least. I'll try to get to that ASAP

**Comment by robfletcher** [comment]
I'd like to memoize the function but that's not possible given it's context comes from a generated stack trace (which is the performance issue). Scratching my head for ideas. It might make sense to be able to flag this behavior off.

**Comment by robfletcher** [comment]
@tmohme-hypoport what do you think of using `-Dstrikt.disableReflection=true` to turn this behavior off?

**Comment by tmohme-hypoport** [comment]
I'm not convinced that a global all-or-nothing flag is the way to go.

After we became aware of strikt's time-consuming behaviour when using the "get with lambda" way to access the values, we had no problem to change most of them to the property-form that doesn't come with the time-penalty and the few that are left aren't worth bothering.
We still use the slow "get with lambda" variant where it gives us an advantage (and are happy with the provided failure-messages), but now we take care to use the faster "get with property" wherever possible.
We naively stumbled into this simply because we weren't making informed decisions which variant to use and "get with lambda" was convenient because we could get nearly everything done with it.

Lazy evaluation (or something alike) would be nice, but if it's not achievable with acceptable effort / increase in (internal) complexity, I would nearly be just as happy with a documentation change.
I think, just putting "get with property reference" first and adding a more prominent note about the cost of "get with lambda" would go a long way to nudge most people in the right direction.
I guess many people are like me: Reading the docs just to the point where they find a solution for their problem. In this case it unfortunately meant not attentively enough reading  the next paragraph describing an even better solution.
