### ISSUE TITLE
Can not add strikt additional libraries dependecy with jcenter

### ISSUE THREAD

**Issue by lenguyenthanh** [robfletcher/strikt#183]
I tried to use `testImplementation("io.strikt:strikt-java-time:0.22.2") but failed because gradle couldn't find it in jcenter.

After I added `maven("https://dl.bintray.com/robfletcher/maven")` to my list of repositories, It worked fine. So it seems strikt additional libraries are not synced to jcenter.

P/s: `strikt-core` works well with jcenter.

**Comment by robfletcher** [comment]
That's weird. I see the artifacts at https://jcenter.bintray.com/io/strikt/strikt-java-time/0.22.2/

**Comment by lenguyenthanh** [comment]
Sorry, I put the wrong dependency, `strikt-arrow` is not on jcenter. https://jcenter.bintray.com/io/strikt/ doesn't have `strikt-arrow`.

**Comment by robfletcher** [comment]
Ah, sorry. I thought I checked all of them but missed that. I've requested Bintray link it. Will close this once I get notified it's there.

**Comment by robfletcher** [comment]
Ok, strikt-arrow is there now. Sorry for the confusion. I wish there was a better way to automate syncing new modules on Bintray.
