### ISSUE TITLE
Make `expectThat(subject, block)` return `Unit`

### ISSUE THREAD

**Issue by Waltorw** [robfletcher/strikt#190]
Hi! Can you please consider making `expectThat(subject, block)` return `Unit` instead of `DescribeableBuilder`. Or add different `Unit` returning method with the same behaviour.

The problem is when using this method in test which body is basically `runBlocking` suspend block. In this case if the assertion is the last statement the block returns the `DescribeableBuilder` from the test method, and JUnit doesn't call non `void` (non `Unit` in this case) test methods during test phase.

**Comment by robfletcher** [comment]
Yeah, that seems reasonable. I'll check that it's not breaking anything vital.
