### ISSUE TITLE
Map value under test

### ISSUE THREAD

**Issue by pmwmedia** [robfletcher/strikt#196]
How can I map a single value under test?

I would like to write a test like that:

```kotlin
val folder: String? = receiveNullableFolder()
expectThat(folder).isNotNull().map { Path.get(it) }.isDirectory()
```

**Comment by robfletcher** [comment]
`.get { Path.get(it) }`

`get` not `map` for single values. It would be difficult to call it `map` as that has different behavior on a `Assertion.Builder<Iterable<*>>` (transforming each individual element).

**Comment by pmwmedia** [comment]
@robfletcher Unfortunately, `get` doesn't work neither:

```
expectThat(folder).isNotNull().get { Paths.get(it) }.isDirectory()
``` 

Error: *Unresolved reference: it*

**Comment by pmwmedia** [comment]
Edit: It works with `this` :)

```kotlin
expectThat(folder).isNotNull().get { Paths.get(this) }.isDirectory()
```

**Comment by robfletcher** [comment]
Yeah, I kind of regret the decision to use a receiver there. Would be a breaking change to adjust it now, tho. If I use both receiver and parameter, it would break the ability to use a property/method reference.
