### ISSUE TITLE
Having trouble with custom assertions

### ISSUE THREAD

**Issue by ejhobbs** [robfletcher/strikt#201]
Hi Folks,

I've been using strikt in a project and have come to a point where I would like to use the custom assertion feature. Up to now my "custom" assertion has looked like this:

```kotlin
fun assertResult(e: Outcome, r: Response<out Any>) {
        expectThat(r.outcome).isEqualTo(e)
    }
```

I rewrote the assertion following the guide on the website, and have ended up with the following:

```kotlin
fun Assertion.Builder<Response<out Any>>.hasOutcome(o: Outcome) =
        assert("has outcome of $o") {
            when (it.outcome) {
                o -> pass()
                else -> fail(actual = it.outcome)
            }
        }
```

This seems to compile fine, however when I actually try and use it I get this error:

```kotlin
expectThat(subject.execute(request, ::id))
            .hasOutcome(Outcome.INVALID_DATA)

//Error:(35, 9) Kotlin: Type mismatch: inferred type is DescribeableBuilder<Response<Brand>> but Assertion.Builder<Response<out Any>> was expected
```

I can see that DescribeableBuilder<T> does inherit from Assertion.Builder<T>, however it doesn't seem to be able to see the extension methods. If I add an extra assertion in front of my custom one it works fine like so:

```kotlin
expectThat(subject.execute(request, ::id))
            .isA<Response<out Any>>()
            .hasOutcome(Outcome.INVALID_DATA)
```
However I don't think this should be necessary? Any help is much appreciated!

update:
Changing the signature to

```kotlin
    fun <T> Assertion.Builder<Response<T>>.hasOutcome(o: Outcome) =
        assert("has outcome of $o") {
            when (it.outcome) {
                o -> pass()
                else -> fail(actual = it.outcome)
            }
        }
```
then works, but I'm not entirely sure why since I would have thought that <out Any> would match any object, regardless of generics?

**Comment by robfletcher** [comment]
I believe if the generic type of `Response` is irrelevant to the assertion function's implementation you should just declare it as `Assertion.Builder<Response<*>>`. Does that work?

**Comment by ejhobbs** [comment]
Thanks for the response, I double checked with the kotlin generics docs and the ```Response<*>``` type seems to be the correct solution, however I still get a similar error:

```
Error:(64, 9) Kotlin: Type mismatch: inferred type is DescribeableBuilder<Response<Brand>> but Assertion.Builder<Response<*>> was expected
```

I can't do a proper investigation right now since I'm in the UK and it's late here, but I'll try to get a toy example working tomorrow. I think the issue may have something to do with there not being an upper limit to T in Response<T>, as all star-projection examples do have upper limits (ie I think it's my types, not strikt!), but I'll hopefully get something more concrete then. One thing that does stand out though is the fact that the type system is picking up DescribeableBuilder rather than Assertion.Builder (even with explicit return types on the assertion), is that something that you would expect? I'm not quite 100% on the difference between them.

**Comment by robfletcher** [comment]
Yeah, that is strange. I'm surprised I haven't run into this myself. If you can get a simple example that recreates the behavior I'd be more than happy to see if I can fix it.

`DescribableBuilder` really exists just to try to limit the scope of when it makes sense to call `describedAs` although I'm not sure how useful that really is. I'd be open to dropping that sub-type if it makes implementing custom assertions awkward.

No worries on the time (I'm originally from the UK too). I'm not sure I'll be able to dedicate any time to fixing this until the weekend anyway.

**Comment by ejhobbs** [comment]
Created a sample repo here: https://github.com/ejhobbs/strikt_assertion_poc

Tried to cover as many bases as possible, so there's: `<Any>`, `<out Any>` and `<T>` variants of each method, inline vs not and `Assertion.Builder<>` vs `DescribeableBuilder<>`. The assertion logic is exactly the same each time to avoid any issues with that. There's also various forms of BucketT however due to compiling down to jvm they can't all exist at the same time so 2/3 are commented out and can be swapped out, however the behaviour remains the same across all 3.

The `<T>` variants seem to be the only methods that work across all 36 possibilities, the others all failing with the exact same error as before (although the "but ... was expected" changes of course). At the very least, it looks as though the difference between Describeable/Assertion doesn't change things.

If you need any more information than this I'm happy to provide, I'm still getting to used to the gotchas with generics so I may have missed something

**Comment by ejhobbs** [comment]
One final piece that I forgot from the initial problem, adding that ```isA<Bucket<out Any>>()``` before the assertion also fixes the error, and does so for both `Bucket<Any>` and `<Bucket<out Any>>.

**Comment by robfletcher** [comment]
I'll try to dig into this over the weekend

**Comment by robfletcher** [comment]
I don't think there's any way to avoid this and there's the additional issue that Strikt's assertions are designed to chain, so they typically return either the `this` `Assertion.Builder` or something derived from it. In order for the former case to work with a flexible type the assertion function really needs to use a generic type.
