### ISSUE TITLE
get { ... } auto-descriptions do not work on windows

### ISSUE THREAD

**Issue by MartinHaeusler** [robfletcher/strikt#202]
Hi,

strikts feature to display the actual code passed into a `get { thisAndThat }` is extremely useful. It's also okay to display the object value as a fallback if the resolver doesn't produce a result. However, under windows, the resolver fails very often for a simple reason:

`FilePeek.kt`, lines 30 - 36: Here you check for things like `"/out/"`, but when running under windows, the variable `classFilePath` contains backslashes (`\`) instead as separators.

Could you please replace the hard-coded `/` characters by `File.separator` to make it work under windows too?

Thanks.

**Comment by robfletcher** [comment]
I think that would need to be a change in christophsturm/filepeek

**Comment by MartinHaeusler** [comment]
You're absolutely right; I didn't notice that this class belongs to a different package when I was looking through the code. I'll forward the issue to that package.

**Comment by MartinHaeusler** [comment]
FYI I've created a [Pull Request](https://github.com/christophsturm/filepeek/pull/5) to the FilePeek library which addresses this issue. I hope it will be accepted / merged / published.

By the way, the library is really just two files, less than 100 lines of code... maybe it would be an option to incorporate the source code directly into strikt, crediting the original author in a KDoc comment of course.

**Comment by robfletcher** [comment]
IIRC it originally was part of Strikt, contributed by the author and he later pulled it out to a separate library. Is that right @christophsturm ?

**Comment by christophsturm** [comment]
right. thanks for the pr, i released version 0.1.2 with your fixes, @MartinHaeusler 
Sorry that it took so long i somehow missed your pr before.

**Comment by MartinHaeusler** [comment]
@christophsturm no worries, the PR was just created a couple of hours ago. I reported the windows issue on your repo a while back, and since I got no response I decided to take action on my own. Thanks for releasing the new version!
