### ISSUE TITLE
`expectCatching` seems badly named

### ISSUE THREAD

**Issue by tom-jb** [robfletcher/strikt#207]
The following code expects an exception to be thrown:

    expectCatching {
        doSomething()
    }.failed()

However, it reads like it does the opposite: "expect catching… failed". I would expect that catching had failed because no exception was thrown!

What about a rename to something like `expectRunning`? That seems clearer:

    expectRunning {
        doSomething()
    }.failed()

"Expect running failed."

**Comment by qoomon** [comment]
maybe you like my extension functions for `Result<T>` see https://github.com/robfletcher/strikt/pull/214

**Comment by robfletcher** [comment]
It's named that way because of the underlying `runCatching` method from the Kotlin stdlib.
