### ISSUE TITLE
Provide `isAn` to match `isA`

### ISSUE THREAD

**Issue by tom-jb** [robfletcher/strikt#208]
`isA` doesn't always read well:

````kotlin
expectThat(foo).isA<Expression>()
````

This is nicer:

````kotlin
expectThat(foo).isAn<Expression>()
````

Anyone could, of course, create their own `isAn` function which simply calls `isA`, but it would be nice if Strikt provided both.

**Comment by robfletcher** [comment]
It's hard to phrase this neutrally. `isInstanceOf` would work but it's kinda verbose. I'm not really in favor of adding a grammatical overload though.
