### ISSUE TITLE
expectThrows / expectCatching warning: Inappropriate blocking method call 

### ISSUE THREAD

**Issue by gotson** [robfletcher/strikt#219]
I am trying to migrate some of my code from asserJj over to strikt, but i'm having a hard time with tests expecting exceptions.

Here is an existing test using assertJ:

```kotlin
@Test
  fun `when adding library with non-existent root folder then exception is thrown`() {
    // when
    val thrown = catchThrowable { libraryLifecycle.addLibrary(Library("test", "/non-existent")) }

    // then
    assertThat(thrown).isInstanceOf(FileNotFoundException::class.java)
  }
```

Here is what i managed to come up with strikt:

```kotlin
@Test
  fun `when adding library with non-existent root folder then exception is thrown`() {
    // then
    expectThrows<FileNotFoundException> { libraryLifecycle.addLibrary(Library("test", "/non-existent")) }
  }
```

I have 2 issues with the code above:

1. IntelliJ is showing a code inspection warning on the `addLibrary` method: Inappropriate blocking method call 
2. I don't know how to separate the _when_ from the _then_ (BDD style). How can I capture a throwable, then do an assertion on it (like with assertJ) ?

Thanks

**Comment by qoomon** [comment]
You can use the native method `runCatching`, see my pull request for examples and convenient methods for `Result` type https://github.com/robfletcher/strikt/pull/214

**Comment by robfletcher** [comment]
1. I will investigate.
2. You can use `expectCatching { ... }` which returns an assertion builder over a `Result<T>` (where `T` is the expected return type of whatever's in the closure).

**Comment by robfletcher** [comment]
@gotson is `addLibrary` a suspending function?

**Comment by gotson** [comment]
No, I don't use coroutines in this project.
