### ISSUE TITLE
throwsMany alike to returnsMany

### ISSUE THREAD

**Issue by qoomon** [robfletcher/strikt#221]
would be great if there is a `throwsMany` function to throw exception in given order for each invocation

**Comment by qoomon** [comment]
In my scenario I need to test a retry mechanism that does a retry on certain exceptions in a given order.

**Comment by robfletcher** [comment]
Can you give me an example of what that would look like? I don't really understand what you want to assert in the test. It sounds to me like something I'd try to handle with a mock / stub interaction, but I might not be visualizing exactly what you mean.

**Comment by qoomon** [comment]
never mind
