### ISSUE TITLE
Failures for not() do not report the actual value

### ISSUE THREAD

**Issue by dhleong** [robfletcher/strikt#222]
For example, `expectThat(...).get(Screen::contents).contains()` might result in:

```
▼ Expect that Screen@453d496b:
  ▼ contents:
    ✗ contains "error"
         found "My value
               |
               |Success
               |"
```

but adding `not()` in there results in simply:

```
▼ Expect that Screen@191a709b:
  ▼ contents:
    ✗ does not contain "error"
```

**Comment by robfletcher** [comment]
This is to some extent dependent on how individual assertions are implemented, but I've updated the framework and all the assertions in the standard library to support this.

**Comment by dhleong** [comment]
Awesome, thank you!
