### ISSUE TITLE
How Strikt different from other Kotlin assertion libraries?

### ISSUE THREAD

**Issue by kaushalyap** [robfletcher/strikt#235]
Other Kotlin assertion libraries
- https://github.com/MarkusAmshove/Kluent
- https://github.com/willowtreeapps/assertk
- https://github.com/hamcrest
- [Kotest](https://github.com/kotest/kotest) assertions

**Comment by robfletcher** [comment]
Feel free to jump into the Slack channel to ask this kind of thing. It's not an issue, though.

**Comment by kaushalyap** [comment]
@robfletcher I do not use Slack, please explain the differences here if you can.
Thanks in advance!
