### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by alvindizon** [robfletcher/strikt#238]
JCenter will be shut down on May, see this article: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by robfletcher** [comment]
Fixed in 21b007caa0e7198ca6c0b6353b84356a4bcc9e02

v0.28.2 is available on Maven Central, and future releases will be published via Sonatype.

**Comment by jschneider** [comment]
Could you publish old versions of the library also on Maven central.

I am sure this would be helpful for a lot of users that did not yet upgrade to the latest version

**Comment by robfletcher** [comment]
Unfortunately I had an incompatibility in older versions of the POM files that means the export from Bintray to Sonatype doesn't work.
