### ISSUE TITLE
Suggestion: assertion builder for "isContainedIn(Collection)"

### ISSUE THREAD

**Issue by MartinHaeusler** [robfletcher/strikt#240]
It's quite common to assert that a given element is contained in a given collection. The subject in this case is the element, *not* the collection. It's like the "contains" assertion, but with the roles of subject and object swapped.

**Comment by robfletcher** [comment]
Thanks for the suggestion. This will be in the next release.

**Comment by MartinHaeusler** [comment]
Great to see that, thank you!
