### ISSUE TITLE
version on maven central use dependency vesion not on maven central

### ISSUE THREAD

**Issue by weaselflink** [robfletcher/strikt#242]
Recently when jcenter was not available my project using strikt-core version 0.29.0 (available from maven central) would not compile. This is because it uses com.christophsturm:filepeek:0.1.2 which is only available on jcenter.

Manually adding com.christophsturm:filepeek:0.1.3 to my project dependencies fixed the issue for me. I suggest switching to filepeek 0.1.3 (available from maven central).

**Comment by robfletcher** [comment]
Yep. I'm working on it. I got some errors from Sonatype uploading some of the modules and haven't had a chance to go back and fix it, but there will be a 0.30.0 soon that will be 100% resolvable from Maven Central.

**Comment by weaselflink** [comment]
Good to hear. Since the workaround is really easy, there is no big hurry.
