### ISSUE TITLE
isExist assertion

### ISSUE THREAD

**Issue by kemalturk** [robfletcher/strikt#245]
The value could be null or not null. I would like to check is value exist. Would it be possible to add isExist assertion?

**Comment by robfletcher** [comment]
There's already `isNotNull()`. Is what you want different to that?

**Comment by kemalturk** [comment]
```
{
  "id": 1,
  "name": null,
}
```
I was thinking that kind of situation. name could be null but i wanna check is key exist. But i think it is not possible in Kotlin way right? I thought like javascript sorry. Im closing the issue.
