### ISSUE TITLE
“Golden Depths” not available on Maven

### ISSUE THREAD

**Issue by ToastShaman** [robfletcher/strikt#248]
The latest release called "Golden Depths" doesn't seem to be pushed to Maven Central. It's only mentioned on the GitHub release pages and can't be found in Maven Central. The website doesn't mention the release either.

**Comment by robfletcher** [comment]
Yeah, there was an error publishing to Sonatype I'm trying to get to the bottom of

**Comment by robfletcher** [comment]
Looks like the keyserver I had uploaded my public key to is no longer active. Hopefully it's propagating to Maven Central now.

**Comment by robfletcher** [comment]
Okay, it's there now
