### ISSUE TITLE
Allow providing custom error messages

### ISSUE THREAD

**Issue by rohandhruva** [robfletcher/strikt#40]
On assertion fails, it would be really useful to have custom error messages prepended to the regular output. 

Currently, a workaround is using `subjectDescription`:

```kotlin
expect("loading view should be gone: %s", loadingView.visibility).isEqualTo(View.GONE)
```

Here's what other libraries do: 

```java
// Google-truth
assertWithMessage("My custom message on failure")
  .that(view)
  .isNotNull();
```

```java
// AssertJ
assertThat(view)
  .as("My custom message)
  .isNotNull()
```

**Comment by robfletcher** [comment]
#33 is relevant here

**Comment by robfletcher** [comment]
As of 7ec0118 you can use `describedAs` to do this.

**Comment by rohandhruva** [comment]
Great, thank you so much, @robfletcher!
