### ISSUE TITLE
expect {...}.throws works only when the block returns unit

### ISSUE THREAD

**Issue by christophsturm** [robfletcher/strikt#61]
```
        expect {}.throws<java.lang.RuntimeException>() // this works
        expect {"blah"}.throws<java.lang.RuntimeException>() // this is red in idea
        throws<RuntimeException> {"blah"} // this works
```

this is a really strange problem, the kotlin compiler seems to be fine with a ()-> Unit block returning something in line 3 but in line 2 it complains

**Comment by robfletcher** [comment]
Weird. I wonder if I widen the return type of the lambda it will fix things.

**Comment by robfletcher** [comment]
I think the only way to solve this is to add a 2nd generic type parameter to `throws` but that means you'd have to specify it along with the exception type.

**Comment by robfletcher** [comment]
The widest I can get the type is `Assertion.Builder<Function<*>>` but even then it doesn't work. Not sure what I can actually do about this.

**Comment by xhanin** [comment]
I have the same problem, my workaround:
```
fun done() {}
expect {"blah"; done()}.throws<java.lang.RuntimeException>()
```

In such example it doesn't make much sense, but if you have a bigger block in expect and the last statement returns something this `done()` call makes it return `Unit` as expected by the API

**Comment by christophsturm** [comment]
@xhanin instead of defining that function you can also just write `;Unit` at the end of the block.

i think that this is a bug in the kotlin compiler. ()->Unit is usually totally fine with methods that return something, thats why line 3 from my original example works. maybe we just need to create a reduces test case and submit an issue in youtrack.

**Comment by xhanin** [comment]
I think the problem is that the compiler can't infer a `()->Unit` type for the function when `expect` is called, while with your third example it can infer it directly for `throws`.

Saying that I found another workaround:
```
expect<()->Unit> {"blah"}.throws<java.lang.RuntimeException>()
```

And yet another one:
```
fun expecting(subject: ()->Unit): DescribeableBuilder<()->Unit> =
        expect(subject)

expecting {"blah"}.throws<java.lang.RuntimeException>()
```

**Comment by christophsturm** [comment]
I also think that that is what happens, and that's why we should create an issue in youtrack for that.

**Comment by christophsturm** [comment]
i submitted a youtrack issue for this https://youtrack.jetbrains.com/issue/KT-26063
