### ISSUE TITLE
should numbers be equal to numbers of different type?

### ISSUE THREAD

**Issue by christophsturm** [robfletcher/strikt#62]
I think that `expect(1L).isEqualTo(1)` should pass, because its an implementation detail that its a long. 
also `1L == 1` is true. 
most other assertion libs seem to not agree with me here, just putting it up for discussion.

maybe isEqualTo should be changed to take `T?` (or a subtype of T?) instead of `Any?`?
it boils down to the question, should isEqualTo work like the `==` operator, or like the `equals` method.
right now the docs say that it works like `==` but in reality it works like `equals`, and i think it would be better if it worked like `==`

**Comment by robfletcher** [comment]
I think you’re right. Semantics should follow `==`.

At the same time I should add a strict equality assertion. Or maybe it’s enough to do `isA<Long>().isEqualTo(5)`.

Not sure I understand the point of changing the generic type.

**Comment by christophsturm** [comment]
i want to change the isEqualTo type because then numbers would be automatically coerced

also it would make `expect("blah").isEqualTo(1)` impossible, like `1 == "blah"`.

**Comment by robfletcher** [comment]
Trouble is, Kotlin won't type coerce. If I change the type to `isEqualTo(T?)` then `expect(1L).isEqualTo(1)` doesn't get coerced, it just won't compile.

**Comment by christophsturm** [comment]
hmm it seems that you are right, but still maybe its better to use T? instead of Any?. it will help you to write the assertion correctly, and avoid that you write something that fails unexpectedly at runtime

**Comment by robfletcher** [comment]
0.11.0 has `isEqualTo` and `isNotEqualTo` take `T?` instead of `Any?`.
