### ISSUE TITLE
Add assertions for Throwable

### ISSUE THREAD

**Issue by xhanin** [robfletcher/strikt#64]
When you want to check the exception that has been thrown in a block you often want to verify the message.  So I defined this:
```
val <T : Throwable> Assertion.Builder<T>.message: Assertion.Builder<String>
    get() = map(Throwable::message).isNotNull()
```

so that I can do this:
```
expect { doSomething() }.throws<IllegalArgumentException>().message.contains("whatever")
```

Maybe that would be something useful in strikt?

**Comment by robfletcher** [comment]
Perfect
