### ISSUE TITLE
Does it make sense to have an expect block with no subject?

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/strikt#69]
Currently `expect` takes a subject parameter. There's no way to group assertions on multiple subjects (at least without abusing `Assertion.Builder.map`).

Does it make sense to have a form of `expect` that just takes a block? For example:

```kotlin
expect {
  that("fnord").isLowerCase()
  that("FNORD").isUpperCase()
}
```

The receiver of such a block would be a new interface with just `fun <T> that(subject: T): Assertion.Builder<T>` and `fun <T> that(subject: T, block: Assertion.Builder<T> -> Unit): Unit`.

The main problem would be that method dispatch would be ambiguous between the new `expect` method and the existing `fun <T> expect(subject: T): Assertion.Builder<T>`. One of them would need a different name (or to be removed).

**Comment by christophsturm** [comment]
i think it would be great. maybe make it `softly { expect("blah").isLowerCase() }`, thats what assert-j used iirc.

**Comment by christophsturm** [comment]
or maybe rename `expect` to `expectThat`, and use the block syntax like 
```
expect {
  that("fnord").isLowerCase()
  that("FNORD").isUpperCase()
}
```

it would also make tests nicer to read.

**Comment by christophsturm** [comment]
and here's another way to group asserts, without a block: `expect("fnord").isLowerCase().andThat("FNORD").isUpperCase()`

**Comment by robfletcher** [comment]
I think replicating AssertJ's `softly` would be misleading as `expect` followed by a block is already doing soft asserts. I envisaged that being the default with Strikt as opposed to an add-on (that doesn't actually work with all assertions) in AssertJ.

I like the renaming of `expect` to `expectThat` with an a new `expect`. I'd been considering that exact change but wasn't sure I wanted to break the API. I think it's probably the right thing to do, though.

**Comment by christophsturm** [comment]
It’s also pretty easy to migrate to the new syntax by just defining a method `expect` that calls `expectThat` and then inlining that method. Also I agree about softly it’s just the first thing that came to mind.
