### ISSUE TITLE
[suggestion] Pass subject as parameter to Assertion.Builder callbacks

### ISSUE THREAD

**Issue by cjbrooks12** [robfletcher/strikt#71]
When writing custom assertions, the only way to get the subject is directly from the `Assertion` receiver's `subject` parameter. A more idiomatic, Kotlin-y way to access the subject would be having it passed as the sole argument to the callback, which can be accessed implicitly as the `it` parameter, or be named as needed by the end-user.

The new signature would look something like:

```kotlin
// in strikt/api/Assertion.kt
fun assert(
      description: String,
      expected: Any?,
      assert: AtomicAssertion<T>.(T) -> Unit
    ): Builder<T>
```

Example usage:

```kotlin
fun Assertion.Builder<LocalDate>.isStTibsDay() =
  assert("is St. Tib's Day") {
    when (MonthDay.from(it)) {
      MonthDay.of(2, 29) -> pass()
      else               -> fail()
    }
  }
```

or

```kotlin
fun Assertion.Builder<LocalDate>.isStTibsDay() =
  assert("is St. Tib's Day") { dateUnderTest ->
    when (MonthDay.from(dateUnderTest)) {
      MonthDay.of(2, 29) -> pass()
      else               -> fail()
    }
  }
```

**Comment by robfletcher** [comment]
I’ve been toying with this idea. I think it may well be an improvement.

Maybe allowing mappings with `map((T)->KProperty<R>)` would make sense too. Then `map { it::name }` would be able to automatically get the property name.

**Comment by robfletcher** [comment]
Implemented this on a branch. See f28f3f9. I think it simplifies some things e.g. `Assertion` and derived types no longer require a generic type.

**Comment by robfletcher** [comment]
In implementing this is seems to also make sense to change `map(T.()->R)` to `map((T)->R)` for consistency. Luckily that doesn't break the ability to pass property / method references such as `map(Person::name)` as I guess they look the same at a bytecode level.

I'd like to also introduce a `map((T)->(()->R))` as it would enable a more concise form of property mapping, e.g. `map { it::name }` which is a lot neater than `map(Person::name)` when the type name is long. However, such a method will need a different name as the JVM can't distinguish them.

**Comment by cjbrooks12** [comment]
What would be the advantage of `map { it::name }` over `map { it.name }`? Since there are no parameters passed to the function, a property/method reference will only ever get a property or call a method with no args, so it doesn't really help much.

**Comment by robfletcher** [comment]
It enables Strikt to add the property name to the assertion message.

**Comment by robfletcher** [comment]
Implemented this. It affects `assert`, `compose`, `map` and `passesIf`.
