### ISSUE TITLE
strange "expect that" output for jackson nodes

### ISSUE THREAD

**Issue by christophsturm** [robfletcher/strikt#75]
this code

```
    @Test
    fun `jackson`() {
        val node = jacksonObjectMapper().readTree(""" {"blah":"blerg"} """)
        print(node.toString())
        expect(node).map(JsonNode::isBigDecimal).isTrue()
    }
```

outputs this:
```
{"blah":"blerg"}

Expected :true
Actual   :false
 <Click to see difference>



strikt.internal.opentest4j.CompoundAssertionFailure: ▼ Expect that [[]]:
  ▼ Expect that .isBigDecimal false:
    ✗ is true : found false

```

**Comment by robfletcher** [comment]
Wouldn't you do this?

```kotlin
expect(node).isA<BigDecimal>()
```

**Comment by robfletcher** [comment]
Can you give an example of what you think it should look like?

**Comment by christophsturm** [comment]
I think it should look like the `tostring` output that I included on top, And not like it does currently: `[[]]`.

**Comment by christophsturm** [comment]
I'm going to do a pr for this

**Comment by robfletcher** [comment]
I think the `[[]]` must be the result of the way JsonNode's toString behaves.

I was thinking it will be necessary to have an extensible formatter for types strikt-core is not aware of. Right now I'm just using a when statement. See: https://github.com/robfletcher/strikt/blob/master/strikt-core/src/main/kotlin/strikt/internal/reporting/Formatting.kt#L22-L40

**Comment by christophsturm** [comment]
the toString is fine but it's also iterable and the iterable output is not very useful

**Comment by christophsturm** [comment]
strikt could check if the class has an own toString method that is not inherited, and prefer that to Iterable
